export const List = [
  {
    heading: `Linux Foundation Mentee at CNCF - Kyverno`,
    logo: 'kyverno.png',
    src: 'https://kyverno.io/',
    alt: 'Linux Foundation Mentee at CNCF - Kyverno',
    date: `Sep'21 - Dec'21`,
    desc: `Kyverno is a kubernetes native policy management engine. I got accepted as an LFX mentee for the fall batch of 2021 where I worked on extending Kyverno’s test commands to cover generate policies and improving test coverage. `,
  },
  {
    heading: `Open-source contributor at Kubernetes`,
    logo: 'k8s.svg',
    src: 'https://kubernetes.io/',
    alt: 'Linux Foundation Mentee at CNCF - Kyverno',
    date: `Sep'21 - NOW`,
    desc: `Being an official member of the Kubernetes organisation, I contribute to its projects, mainly sig‐contribex, sig-k8s-infra, and upstream kubernetes.`,
  },
  {
    heading: `GitHub Campus Expert - NIT Rourkela`,
    logo: 'gce.png',
    src: 'https://education.github.com/experts',
    alt: 'Linux Foundation Mentee at CNCF - Kyverno',
    date: `Oct'21 - NOW`,
    desc: `Campus Experts are student leaders that strive to build diverse and inclusive spaces to learn skills, share their experiences, and build projects together.`,
  },
  {
    heading: `Backend Developer, Open Bioinformatics Fdn.`,
    logo: 'obf.png',
    src: 'https://www.open-bio.org/',
    alt: 'Open Bioinformatics Foundation',
    date: `Jun'21 - Aug'21`,
    desc: `The Open Bioinformatics Foundation (OBF) is a non-profit, volunteer-run group that promotes open source software development and Open Science within the biological research community. `,
  },
  {
    heading: `Core Team, Google DSC NIT Rourkela`,
    logo: 'gdsc.png',
    src: 'https://dscnitrourkela.org/',
    alt: 'GDSC NIT Rourkela',
    date: `Dec'20 - Now`,
    desc: `Google Developer Student Club is a Google Developers program intended as a space for
 students to try out new ideas and collaborate to solve mobile and web development problems.`,
  },
  {
    heading: `Community Manager, OpenCode NITR`,
    logo: 'opencode.png',
    src: 'https://opencodenitr.herokuapp.com/',
    alt: 'Opencode NIT Rourkela',
    date: `Jul'21 - Now`,
    desc: `OpenCode is the open source community of NIT Rourkela. It a community of student developers/coders, dedicated to contributing to the open-source community through the skills they acquire in our learning process.`,
  },
  {
    heading: `Technical Lead, HackNITR 2.0`,
    logo: 'hacknitr.png',
    src: 'https://hacknitr.tech/',
    alt: 'HackNITR Hackathon',
    date: `Jan'21 - Mar'21`,
    desc: `HackNITR, one of the largest hackathons in India's eastern region, is a kind of hackathon that endeavours to bring and integrate talent, innovation and creativity under on roof to build solutions for the real world problems using latest technologies.`,
  },
  {
    heading: `Mentor, Hack The 6ix Hackathon`,
    logo: 'ht6.svg',
    src: 'https://hackthe6ix.com/',
    alt: 'Hack The 6ix Hackathon',
    date: `20-22 Aug, 2021`,
    desc: `Hack the 6ix is the largest summer student run, not-for-profit 36 hour hackathon which is now in its seventh iteration, based in Toronto, Canada.`,
  },
  {
    heading: `Winter of Code Student @eduAlgo`,
    logo: 'winterofcode.png',
    src: 'https://winterofcode.com/',
    alt: 'Winter of Code by DSC NSEC',
    date: `Nov'20 - Jan'21`,
    desc: `Winter of Code, an initiative by GDSC NSEC, aimed to increase participation for the Google Summer of Code program among students in colleges and universities.`,
  },
  {
    heading: `Freelancer, Humaps`,
    logo: 'humaps.jpeg',
    src: 'https://www.humaps.in/',
    alt: 'Winter of Code by DSC NSEC',
    date: `Nov'20 - Dec'20`,
    desc: `Humaps is a team of developers by profession and passionate people who thrive to build apps that suits perfectly to individuals.`,
  },
  {
    heading: `Angelhack Student Ambassador`,
    logo: 'angelhack.png',
    src: 'https://angelhack.com/',
    alt: 'Angelhack Student Ambassador',
    date: `Sep'21 - NOW`,
    desc: `Student Lead from the AngelHack Campus Hub - NIT, Rourkela. Engaging with local developer communities to strengthen local ecosystems, bring together passionate individuals, and promote innovation.`,
  },
  {
    heading: `Postman Student Expert, Postman`,
    logo: 'postman.svg',
    src: 'https://www.postman.com/company/student-program/',
    alt: 'Postman Student Expert',
    date: `May'21 - NOW`,
    desc: `Postman Student Experts are Postman Certified Experts who are proficient in the essential skills involved in building,
    maintaining, monitoring and testing API requests, collections and workspaces in Postman`,
  },
];
