export const List = [
  {
    heading: `Backend Developer, OBF (Jun'21 - Aug'21)`,
    logo: 'obf.png',
    src: 'https://www.open-bio.org/',
    alt: 'Open Bioinformatics Foundation',
    desc: `The Open Bioinformatics Foundation (OBF) is a non-profit, volunteer-run group that promotes open source software development and Open Science within the biological research community. `,
  },
  {
    heading: `Core Team, GDSC NIT Rourkela (Dec'20 - NOW)`,
    logo: 'gdsc.png',
    src: 'https://dscnitrourkela.org/',
    alt: 'GDSC NIT Rourkela',
    desc: `Google Developer Student Club is a Google Developers program intended as a space for
 students to try out new ideas and collaborate to solve mobile and web development problems.`,
  },
  {
    heading: `Community Manager, OpenCode NITR (Jul'21 - NOW)`,
    logo: 'opencode.png',
    src: 'https://opencodenitr.herokuapp.com/',
    alt: 'Opencode NIT Rourkela',
    desc: `OpenCode is the open source community of NIT Rourkela. It a community of student developers/coders, dedicated to contributing to the open-source community through the skills they acquire in our learning process.`,
  },
  {
    heading: `Technical Lead, HackNITR 2.0 & 3.0 (Jan'21 - Mar'21)`,
    logo: 'hacknitr.png',
    src: 'https://hacknitr.tech/',
    alt: 'HackNITR Hackathon',
    desc: `HackNITR, one of the largest hackathons in India's eastern region, is a kind of hackathon that endeavours to bring and integrate talent, innovation and creativity under on roof to build solutions for the real world problems using latest technologies.`,
  },
  {
    heading: `Mentor, Hack The 6ix Hackathon (20-22 Aug, 2021)`,
    logo: 'ht6.svg',
    src: 'https://hackthe6ix.com/',
    alt: 'Hack The 6ix Hackathon',
    desc: `Hack the 6ix is the largest summer student-run, not-for-profit hackathon now in its seventh iteration, based in Toronto. It takes pride in the diversity and talent of its hackers, who help them become a key player in the Toronto tech ecosystem.`,
  },
  {
    heading: `Winter of Code Student @eduAlgo (Nov'20 - Jan'21)`,
    logo: 'winterofcode.png',
    src: 'https://winterofcode.com/',
    alt: 'Winter of Code by DSC NSEC',
    desc: `Winter of Code, an initiative by GDSC NSEC, aimed to increase participation for the Google Summer of Code program among students in colleges and universities. As a part of the Winter of Code, students are paired with mentors from the participating organisation.`,
  },
  {
    heading: `Freelancer, Humaps (Nov'20 - Dec'20)`,
    logo: 'humaps.jpeg',
    src: 'https://www.humaps.in/',
    alt: 'Winter of Code by DSC NSEC',
    desc: `Humaps is a team of developers by profession and passionate people who thrive to build apps that suits perfectly to individuals. It's team is passionate about creating and enhancing anything related to technology in general.`,
  },
  {
    heading: `Postman Student Expert, Postman (May'21 - NOW)`,
    logo: 'postman.svg',
    src: 'https://www.postman.com/company/student-program/',
    alt: 'Postman Student Expert',
    desc: `Postman Student Experts are Postman Certified Experts who are proficient in the essential skills involved in building,
    maintaining, monitoring and testing API requests, collections and workspaces in Postman`,
  },
];
