name: Lighthouse_Audit
on: [push, pull_request]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.8.x
          lhci autorun
